//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAIG.PS.ConfigGen.ConfigGen.SwampyProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyPair", Namespace="http://schemas.datacontract.org/2004/07/Swampy.Domain.Contract")]
    [System.SerializableAttribute()]
    public partial class KeyPair : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConfigGen.SwampyProxy.IEndpointService")]
    public interface IEndpointService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEndpointService/GetEndpoints", ReplyAction="http://tempuri.org/IEndpointService/GetEndpointsResponse")]
        SAIG.PS.ConfigGen.ConfigGen.SwampyProxy.GetEndpointsResponse GetEndpoints(SAIG.PS.ConfigGen.ConfigGen.SwampyProxy.GetEndpointsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IEndpointService/GetEndpoints", ReplyAction="http://tempuri.org/IEndpointService/GetEndpointsResponse")]
        System.IAsyncResult BeginGetEndpoints(SAIG.PS.ConfigGen.ConfigGen.SwampyProxy.GetEndpointsRequest request, System.AsyncCallback callback, object asyncState);
        
        SAIG.PS.ConfigGen.ConfigGen.SwampyProxy.GetEndpointsResponse EndGetEndpoints(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEndpointService/GetSingleEndpoint", ReplyAction="http://tempuri.org/IEndpointService/GetSingleEndpointResponse")]
        SAIG.PS.ConfigGen.ConfigGen.SwampyProxy.GetSingleEndpointResponse GetSingleEndpoint(SAIG.PS.ConfigGen.ConfigGen.SwampyProxy.GetSingleEndpointRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IEndpointService/GetSingleEndpoint", ReplyAction="http://tempuri.org/IEndpointService/GetSingleEndpointResponse")]
        System.IAsyncResult BeginGetSingleEndpoint(SAIG.PS.ConfigGen.ConfigGen.SwampyProxy.GetSingleEndpointRequest request, System.AsyncCallback callback, object asyncState);
        
        SAIG.PS.ConfigGen.ConfigGen.SwampyProxy.GetSingleEndpointResponse EndGetSingleEndpoint(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEndpoints", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetEndpointsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string environment;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string[] keys;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string callingApplication;
        
        public GetEndpointsRequest() {
        }
        
        public GetEndpointsRequest(string environment, string[] keys, string callingApplication) {
            this.environment = environment;
            this.keys = keys;
            this.callingApplication = callingApplication;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEndpointsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetEndpointsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SAIG.PS.ConfigGen.ConfigGen.SwampyProxy.KeyPair[] GetEndpointsResult;
        
        public GetEndpointsResponse() {
        }
        
        public GetEndpointsResponse(SAIG.PS.ConfigGen.ConfigGen.SwampyProxy.KeyPair[] GetEndpointsResult) {
            this.GetEndpointsResult = GetEndpointsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSingleEndpoint", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSingleEndpointRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string environment;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string key;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string callingApplication;
        
        public GetSingleEndpointRequest() {
        }
        
        public GetSingleEndpointRequest(string environment, string key, string callingApplication) {
            this.environment = environment;
            this.key = key;
            this.callingApplication = callingApplication;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSingleEndpointResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetSingleEndpointResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SAIG.PS.ConfigGen.ConfigGen.SwampyProxy.KeyPair GetSingleEndpointResult;
        
        public GetSingleEndpointResponse() {
        }
        
        public GetSingleEndpointResponse(SAIG.PS.ConfigGen.ConfigGen.SwampyProxy.KeyPair GetSingleEndpointResult) {
            this.GetSingleEndpointResult = GetSingleEndpointResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEndpointServiceChannel : SAIG.PS.ConfigGen.ConfigGen.SwampyProxy.IEndpointService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetEndpointsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetEndpointsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SAIG.PS.ConfigGen.ConfigGen.SwampyProxy.GetEndpointsResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SAIG.PS.ConfigGen.ConfigGen.SwampyProxy.GetEndpointsResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSingleEndpointCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSingleEndpointCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SAIG.PS.ConfigGen.ConfigGen.SwampyProxy.GetSingleEndpointResponse Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SAIG.PS.ConfigGen.ConfigGen.SwampyProxy.GetSingleEndpointResponse)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EndpointServiceClient : System.ServiceModel.ClientBase<SAIG.PS.ConfigGen.ConfigGen.SwampyProxy.IEndpointService>, SAIG.PS.ConfigGen.ConfigGen.SwampyProxy.IEndpointService {
        
        private BeginOperationDelegate onBeginGetEndpointsDelegate;
        
        private EndOperationDelegate onEndGetEndpointsDelegate;
        
        private System.Threading.SendOrPostCallback onGetEndpointsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetSingleEndpointDelegate;
        
        private EndOperationDelegate onEndGetSingleEndpointDelegate;
        
        private System.Threading.SendOrPostCallback onGetSingleEndpointCompletedDelegate;
        
        public EndpointServiceClient() {
        }
        
        public EndpointServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EndpointServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EndpointServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EndpointServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetEndpointsCompletedEventArgs> GetEndpointsCompleted;
        
        public event System.EventHandler<GetSingleEndpointCompletedEventArgs> GetSingleEndpointCompleted;
        
        public SAIG.PS.ConfigGen.ConfigGen.SwampyProxy.GetEndpointsResponse GetEndpoints(SAIG.PS.ConfigGen.ConfigGen.SwampyProxy.GetEndpointsRequest request) {
            return base.Channel.GetEndpoints(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetEndpoints(SAIG.PS.ConfigGen.ConfigGen.SwampyProxy.GetEndpointsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetEndpoints(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public SAIG.PS.ConfigGen.ConfigGen.SwampyProxy.GetEndpointsResponse EndGetEndpoints(System.IAsyncResult result) {
            return base.Channel.EndGetEndpoints(result);
        }
        
        private System.IAsyncResult OnBeginGetEndpoints(object[] inValues, System.AsyncCallback callback, object asyncState) {
            SAIG.PS.ConfigGen.ConfigGen.SwampyProxy.GetEndpointsRequest request = ((SAIG.PS.ConfigGen.ConfigGen.SwampyProxy.GetEndpointsRequest)(inValues[0]));
            return this.BeginGetEndpoints(request, callback, asyncState);
        }
        
        private object[] OnEndGetEndpoints(System.IAsyncResult result) {
            SAIG.PS.ConfigGen.ConfigGen.SwampyProxy.GetEndpointsResponse retVal = this.EndGetEndpoints(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetEndpointsCompleted(object state) {
            if ((this.GetEndpointsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetEndpointsCompleted(this, new GetEndpointsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetEndpointsAsync(SAIG.PS.ConfigGen.ConfigGen.SwampyProxy.GetEndpointsRequest request) {
            this.GetEndpointsAsync(request, null);
        }
        
        public void GetEndpointsAsync(SAIG.PS.ConfigGen.ConfigGen.SwampyProxy.GetEndpointsRequest request, object userState) {
            if ((this.onBeginGetEndpointsDelegate == null)) {
                this.onBeginGetEndpointsDelegate = new BeginOperationDelegate(this.OnBeginGetEndpoints);
            }
            if ((this.onEndGetEndpointsDelegate == null)) {
                this.onEndGetEndpointsDelegate = new EndOperationDelegate(this.OnEndGetEndpoints);
            }
            if ((this.onGetEndpointsCompletedDelegate == null)) {
                this.onGetEndpointsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetEndpointsCompleted);
            }
            base.InvokeAsync(this.onBeginGetEndpointsDelegate, new object[] {
                        request}, this.onEndGetEndpointsDelegate, this.onGetEndpointsCompletedDelegate, userState);
        }
        
        public SAIG.PS.ConfigGen.ConfigGen.SwampyProxy.GetSingleEndpointResponse GetSingleEndpoint(SAIG.PS.ConfigGen.ConfigGen.SwampyProxy.GetSingleEndpointRequest request) {
            return base.Channel.GetSingleEndpoint(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetSingleEndpoint(SAIG.PS.ConfigGen.ConfigGen.SwampyProxy.GetSingleEndpointRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSingleEndpoint(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public SAIG.PS.ConfigGen.ConfigGen.SwampyProxy.GetSingleEndpointResponse EndGetSingleEndpoint(System.IAsyncResult result) {
            return base.Channel.EndGetSingleEndpoint(result);
        }
        
        private System.IAsyncResult OnBeginGetSingleEndpoint(object[] inValues, System.AsyncCallback callback, object asyncState) {
            SAIG.PS.ConfigGen.ConfigGen.SwampyProxy.GetSingleEndpointRequest request = ((SAIG.PS.ConfigGen.ConfigGen.SwampyProxy.GetSingleEndpointRequest)(inValues[0]));
            return this.BeginGetSingleEndpoint(request, callback, asyncState);
        }
        
        private object[] OnEndGetSingleEndpoint(System.IAsyncResult result) {
            SAIG.PS.ConfigGen.ConfigGen.SwampyProxy.GetSingleEndpointResponse retVal = this.EndGetSingleEndpoint(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSingleEndpointCompleted(object state) {
            if ((this.GetSingleEndpointCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSingleEndpointCompleted(this, new GetSingleEndpointCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSingleEndpointAsync(SAIG.PS.ConfigGen.ConfigGen.SwampyProxy.GetSingleEndpointRequest request) {
            this.GetSingleEndpointAsync(request, null);
        }
        
        public void GetSingleEndpointAsync(SAIG.PS.ConfigGen.ConfigGen.SwampyProxy.GetSingleEndpointRequest request, object userState) {
            if ((this.onBeginGetSingleEndpointDelegate == null)) {
                this.onBeginGetSingleEndpointDelegate = new BeginOperationDelegate(this.OnBeginGetSingleEndpoint);
            }
            if ((this.onEndGetSingleEndpointDelegate == null)) {
                this.onEndGetSingleEndpointDelegate = new EndOperationDelegate(this.OnEndGetSingleEndpoint);
            }
            if ((this.onGetSingleEndpointCompletedDelegate == null)) {
                this.onGetSingleEndpointCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSingleEndpointCompleted);
            }
            base.InvokeAsync(this.onBeginGetSingleEndpointDelegate, new object[] {
                        request}, this.onEndGetSingleEndpointDelegate, this.onGetSingleEndpointCompletedDelegate, userState);
        }
    }
}
