//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAIG.PS.ConfigGen.SwampyEnvironments {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyPair", Namespace="http://schemas.datacontract.org/2004/07/SAIG.PS.Swampy.Service.Contract")]
    [System.SerializableAttribute()]
    public partial class KeyPair : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SwampyEnvironments.IEndpointService")]
    public interface IEndpointService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEndpointService/GetEndpoints", ReplyAction="http://tempuri.org/IEndpointService/GetEndpointsResponse")]
        SAIG.PS.ConfigGen.SwampyEnvironments.KeyPair[] GetEndpoints(string environment, string[] keys, string callingApplication);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IEndpointService/GetEndpoints", ReplyAction="http://tempuri.org/IEndpointService/GetEndpointsResponse")]
        System.IAsyncResult BeginGetEndpoints(string environment, string[] keys, string callingApplication, System.AsyncCallback callback, object asyncState);
        
        SAIG.PS.ConfigGen.SwampyEnvironments.KeyPair[] EndGetEndpoints(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEndpointService/GetSingleEndpoint", ReplyAction="http://tempuri.org/IEndpointService/GetSingleEndpointResponse")]
        SAIG.PS.ConfigGen.SwampyEnvironments.KeyPair GetSingleEndpoint(string environment, string key, string callingApplication);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IEndpointService/GetSingleEndpoint", ReplyAction="http://tempuri.org/IEndpointService/GetSingleEndpointResponse")]
        System.IAsyncResult BeginGetSingleEndpoint(string environment, string key, string callingApplication, System.AsyncCallback callback, object asyncState);
        
        SAIG.PS.ConfigGen.SwampyEnvironments.KeyPair EndGetSingleEndpoint(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEndpointServiceChannel : SAIG.PS.ConfigGen.SwampyEnvironments.IEndpointService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetEndpointsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetEndpointsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SAIG.PS.ConfigGen.SwampyEnvironments.KeyPair[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SAIG.PS.ConfigGen.SwampyEnvironments.KeyPair[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSingleEndpointCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSingleEndpointCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SAIG.PS.ConfigGen.SwampyEnvironments.KeyPair Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SAIG.PS.ConfigGen.SwampyEnvironments.KeyPair)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EndpointServiceClient : System.ServiceModel.ClientBase<SAIG.PS.ConfigGen.SwampyEnvironments.IEndpointService>, SAIG.PS.ConfigGen.SwampyEnvironments.IEndpointService {
        
        private BeginOperationDelegate onBeginGetEndpointsDelegate;
        
        private EndOperationDelegate onEndGetEndpointsDelegate;
        
        private System.Threading.SendOrPostCallback onGetEndpointsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetSingleEndpointDelegate;
        
        private EndOperationDelegate onEndGetSingleEndpointDelegate;
        
        private System.Threading.SendOrPostCallback onGetSingleEndpointCompletedDelegate;
        
        public EndpointServiceClient() {
        }
        
        public EndpointServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EndpointServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EndpointServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EndpointServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetEndpointsCompletedEventArgs> GetEndpointsCompleted;
        
        public event System.EventHandler<GetSingleEndpointCompletedEventArgs> GetSingleEndpointCompleted;
        
        public SAIG.PS.ConfigGen.SwampyEnvironments.KeyPair[] GetEndpoints(string environment, string[] keys, string callingApplication) {
            return base.Channel.GetEndpoints(environment, keys, callingApplication);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetEndpoints(string environment, string[] keys, string callingApplication, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetEndpoints(environment, keys, callingApplication, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public SAIG.PS.ConfigGen.SwampyEnvironments.KeyPair[] EndGetEndpoints(System.IAsyncResult result) {
            return base.Channel.EndGetEndpoints(result);
        }
        
        private System.IAsyncResult OnBeginGetEndpoints(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string environment = ((string)(inValues[0]));
            string[] keys = ((string[])(inValues[1]));
            string callingApplication = ((string)(inValues[2]));
            return this.BeginGetEndpoints(environment, keys, callingApplication, callback, asyncState);
        }
        
        private object[] OnEndGetEndpoints(System.IAsyncResult result) {
            SAIG.PS.ConfigGen.SwampyEnvironments.KeyPair[] retVal = this.EndGetEndpoints(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetEndpointsCompleted(object state) {
            if ((this.GetEndpointsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetEndpointsCompleted(this, new GetEndpointsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetEndpointsAsync(string environment, string[] keys, string callingApplication) {
            this.GetEndpointsAsync(environment, keys, callingApplication, null);
        }
        
        public void GetEndpointsAsync(string environment, string[] keys, string callingApplication, object userState) {
            if ((this.onBeginGetEndpointsDelegate == null)) {
                this.onBeginGetEndpointsDelegate = new BeginOperationDelegate(this.OnBeginGetEndpoints);
            }
            if ((this.onEndGetEndpointsDelegate == null)) {
                this.onEndGetEndpointsDelegate = new EndOperationDelegate(this.OnEndGetEndpoints);
            }
            if ((this.onGetEndpointsCompletedDelegate == null)) {
                this.onGetEndpointsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetEndpointsCompleted);
            }
            base.InvokeAsync(this.onBeginGetEndpointsDelegate, new object[] {
                        environment,
                        keys,
                        callingApplication}, this.onEndGetEndpointsDelegate, this.onGetEndpointsCompletedDelegate, userState);
        }
        
        public SAIG.PS.ConfigGen.SwampyEnvironments.KeyPair GetSingleEndpoint(string environment, string key, string callingApplication) {
            return base.Channel.GetSingleEndpoint(environment, key, callingApplication);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetSingleEndpoint(string environment, string key, string callingApplication, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSingleEndpoint(environment, key, callingApplication, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public SAIG.PS.ConfigGen.SwampyEnvironments.KeyPair EndGetSingleEndpoint(System.IAsyncResult result) {
            return base.Channel.EndGetSingleEndpoint(result);
        }
        
        private System.IAsyncResult OnBeginGetSingleEndpoint(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string environment = ((string)(inValues[0]));
            string key = ((string)(inValues[1]));
            string callingApplication = ((string)(inValues[2]));
            return this.BeginGetSingleEndpoint(environment, key, callingApplication, callback, asyncState);
        }
        
        private object[] OnEndGetSingleEndpoint(System.IAsyncResult result) {
            SAIG.PS.ConfigGen.SwampyEnvironments.KeyPair retVal = this.EndGetSingleEndpoint(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSingleEndpointCompleted(object state) {
            if ((this.GetSingleEndpointCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSingleEndpointCompleted(this, new GetSingleEndpointCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSingleEndpointAsync(string environment, string key, string callingApplication) {
            this.GetSingleEndpointAsync(environment, key, callingApplication, null);
        }
        
        public void GetSingleEndpointAsync(string environment, string key, string callingApplication, object userState) {
            if ((this.onBeginGetSingleEndpointDelegate == null)) {
                this.onBeginGetSingleEndpointDelegate = new BeginOperationDelegate(this.OnBeginGetSingleEndpoint);
            }
            if ((this.onEndGetSingleEndpointDelegate == null)) {
                this.onEndGetSingleEndpointDelegate = new EndOperationDelegate(this.OnEndGetSingleEndpoint);
            }
            if ((this.onGetSingleEndpointCompletedDelegate == null)) {
                this.onGetSingleEndpointCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSingleEndpointCompleted);
            }
            base.InvokeAsync(this.onBeginGetSingleEndpointDelegate, new object[] {
                        environment,
                        key,
                        callingApplication}, this.onEndGetSingleEndpointDelegate, this.onGetSingleEndpointCompletedDelegate, userState);
        }
    }
}
